#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Next\App;

$config = require __DIR__ . '/next.config.php';
$app = new Next\App($config);

use Symfony\Component\Console\Application;

$application = new Application();

if (!empty($config['commands'])) {
    foreach ($config['commands'] as $class) {
        $application->add(new $class());
    }
}

$application->run();
