#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

$config = require __DIR__ . '/next.config.php';

new \Next\App($config);

$console = new \Symfony\Component\Console\Application();

(new \NunoMaduro\Collision\Provider())->register();

if (isset($config['commands'])) {
    foreach ($config['commands'] as $class) {
        $console->add(new $class());
    }
}

$console->run();
