#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

$config = require __DIR__ . '/next.config.php';

$app = new \Next\App($config);

$console = new \Next\Console\Application($app);

if (isset($config['commands'])) {
    foreach ($config['commands'] as $class) {
        $console->add(new $class());
    }
}

$console->run();
